name: Build & deploy Android app

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release (e.g., v1.0.0)"
        required: true
      release_name:
        description: "Release name (optional)"
        required: false
        default: ""

jobs:
  deployAndroid:
    permissions:
      contents: write
    name: Build & deploy Android release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.jks"
          encodedString: ${{ secrets.KEYSTORE_FILE_BASE64 }}

      - name: Build APK
        run: |
          cd ${{ github.workspace }}/V2rayNG
          chmod 755 gradlew
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Upload APK to release using upload-release-action
        uses: svenstaro/upload-release-action@v2
        with:
          file: app/build/outputs/apk/release/app-release.apk
          tag: ${{ github.event.inputs.tag_name }}
          file_glob: false
